spring:
  application:
    name: ai-code-mother-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code_mother?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 20040609
  session:
    sotre-type: redis
    time-to-live: 2592000
  profiles:
    active: local
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
server:
  port: 8123
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.jay.aicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
langchain4j:
  open-ai:
    streaming-chat-model:
      api-key: {api-key}

